/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ErrorCode } from './errorCode';

export interface ApiErrorResponse {
  details?: string | null;
  code: ErrorCode;
  subCode?: string | null;
}
export namespace ApiErrorResponse {}
