/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CustomAttributeData } from './customAttributeData';
import type { Type } from './type';
import type { SecurityRuleSet } from './securityRuleSet';
import type { MethodInfo } from './methodInfo';
import type { Module } from './module';
import type { TypeInfo } from './typeInfo';

export interface Assembly {
  readonly definedTypes?: Array<TypeInfo> | null;
  readonly exportedTypes?: Array<Type> | null;
  readonly codeBase?: string | null;
  entryPoint?: MethodInfo;
  readonly fullName?: string | null;
  readonly imageRuntimeVersion?: string | null;
  readonly isDynamic?: boolean;
  readonly location?: string | null;
  readonly reflectionOnly?: boolean;
  readonly isCollectible?: boolean;
  readonly isFullyTrusted?: boolean;
  readonly customAttributes?: Array<CustomAttributeData> | null;
  readonly escapedCodeBase?: string | null;
  manifestModule?: Module;
  readonly modules?: Array<Module> | null;
  readonly globalAssemblyCache?: boolean;
  readonly hostContext?: number;
  securityRuleSet?: SecurityRuleSet;
}
export namespace Assembly {}
