/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type ErrorCode =
  | 'Unknown'
  | 'Unauthorized'
  | 'SubscriptionQuotaExceeded'
  | 'Forbidden'
  | 'CompilationFailed'
  | 'WalletServiceTemporaryUnavailable'
  | 'GetContractsFailed'
  | 'UserNotFound'
  | 'FormValidationFailed'
  | 'OrganizationNotFound'
  | 'CannotCreateWallet'
  | 'UserAlreadyExist'
  | 'TokenNotFound'
  | 'SmartContractNotFound'
  | 'WalletNotFound'
  | 'SmartContractNotDeployed'
  | 'SmartContractDeploymentFailed'
  | 'SmartContractCallFailed'
  | 'EstimationFailed'
  | 'PasswordWeak'
  | 'TwoFactorAlreadyEnabled'
  | 'TwoFactorMissingSetup'
  | 'TwoFactorCodeInvalid'
  | 'TwoFactorNotEnabled'
  | 'TwoFactorTooManyFailedAttempts'
  | 'MissingTwoFactorCode'
  | 'BlockchainServiceUnavailable'
  | 'ContractPreparationFailed'
  | 'ActivationMissing'
  | 'BlockchainNotFound'
  | 'BlockchainEndpointNotFound'
  | 'SubscriptionPlanNotFound'
  | 'BlockchainEndpointCreationFailed'
  | 'GetBlockchainEndpointFailed'
  | 'SolCompilerTemporaryUnavailable'
  | 'BlockchainEndpointServiceTemporaryUnavailable'
  | 'GetBlockchainEndpointCallsFailed'
  | 'GetBlockchainEndpointMethodUsageFailed'
  | 'GetBlockchainEndpointUsageFailed'
  | 'GetBlockchainEndpointCallStatsFailed'
  | 'DeleteBlockchainEndpointFailed'
  | 'GetBlockchainEndpointsFailed'
  | 'CannotGetUserInfo'
  | 'UserAuthenticatedWithDifferentMethod'
  | 'InvalidAccessToken'
  | 'CannotActivateAuthMethod'
  | 'RpcCallFailed'
  | 'RpcRequestFailed'
  | 'WalletPasswordNotStrongEnough'
  | 'CannotChangeWalletPassword'
  | 'CannotGenerateSlug'
  | 'UserAlreadyInvited'
  | 'InvitationNotFound'
  | 'InvitationEmailMismatch'
  | 'CannotInviteToPersonalOrganization'
  | 'CannotUpdatePersonalOrganization'
  | 'CannotRemoveYourself'
  | 'MemberNotFound'
  | 'SubscriptionProductNotFound'
  | 'SubscriptionMetadataNotFound'
  | 'PaymentSessionMissing'
  | 'CannotFindActiveSubscription'
  | 'SubscriptionNotFound'
  | 'CannotFindSubscriptionLimit'
  | 'SubscriptionDataMissing'
  | 'GetOrganizationEndpointConsumptionFailed'
  | 'CannotRegisterPushClient'
  | 'OAuthDataIncomplete'
  | 'AppleVerificationFailed'
  | 'OAuthEmailMissing'
  | 'WalletUsedBySmartContracts'
  | 'EmailMissing'
  | 'InvalidCode'
  | 'TemplateNotFound'
  | 'TemplateInputInvalid'
  | 'SmartContractNotBelongToOrganization'
  | 'UserNotActive'
  | 'OrganizationCacheClearFailed'
  | 'CannotReadRequest'
  | 'PaymasterServiceUnavailable'
  | 'CreatePaymasterFailed'
  | 'GetPaymasterFailed'
  | 'UnsupportedFeature'
  | 'PaymasterEndpointNotFound';

export const ErrorCode = {
  Unknown: 'Unknown' as ErrorCode,
  Unauthorized: 'Unauthorized' as ErrorCode,
  SubscriptionQuotaExceeded: 'SubscriptionQuotaExceeded' as ErrorCode,
  Forbidden: 'Forbidden' as ErrorCode,
  CompilationFailed: 'CompilationFailed' as ErrorCode,
  WalletServiceTemporaryUnavailable:
    'WalletServiceTemporaryUnavailable' as ErrorCode,
  GetContractsFailed: 'GetContractsFailed' as ErrorCode,
  UserNotFound: 'UserNotFound' as ErrorCode,
  FormValidationFailed: 'FormValidationFailed' as ErrorCode,
  OrganizationNotFound: 'OrganizationNotFound' as ErrorCode,
  CannotCreateWallet: 'CannotCreateWallet' as ErrorCode,
  UserAlreadyExist: 'UserAlreadyExist' as ErrorCode,
  TokenNotFound: 'TokenNotFound' as ErrorCode,
  SmartContractNotFound: 'SmartContractNotFound' as ErrorCode,
  WalletNotFound: 'WalletNotFound' as ErrorCode,
  SmartContractNotDeployed: 'SmartContractNotDeployed' as ErrorCode,
  SmartContractDeploymentFailed: 'SmartContractDeploymentFailed' as ErrorCode,
  SmartContractCallFailed: 'SmartContractCallFailed' as ErrorCode,
  EstimationFailed: 'EstimationFailed' as ErrorCode,
  PasswordWeak: 'PasswordWeak' as ErrorCode,
  TwoFactorAlreadyEnabled: 'TwoFactorAlreadyEnabled' as ErrorCode,
  TwoFactorMissingSetup: 'TwoFactorMissingSetup' as ErrorCode,
  TwoFactorCodeInvalid: 'TwoFactorCodeInvalid' as ErrorCode,
  TwoFactorNotEnabled: 'TwoFactorNotEnabled' as ErrorCode,
  TwoFactorTooManyFailedAttempts: 'TwoFactorTooManyFailedAttempts' as ErrorCode,
  MissingTwoFactorCode: 'MissingTwoFactorCode' as ErrorCode,
  BlockchainServiceUnavailable: 'BlockchainServiceUnavailable' as ErrorCode,
  ContractPreparationFailed: 'ContractPreparationFailed' as ErrorCode,
  ActivationMissing: 'ActivationMissing' as ErrorCode,
  BlockchainNotFound: 'BlockchainNotFound' as ErrorCode,
  BlockchainEndpointNotFound: 'BlockchainEndpointNotFound' as ErrorCode,
  SubscriptionPlanNotFound: 'SubscriptionPlanNotFound' as ErrorCode,
  BlockchainEndpointCreationFailed:
    'BlockchainEndpointCreationFailed' as ErrorCode,
  GetBlockchainEndpointFailed: 'GetBlockchainEndpointFailed' as ErrorCode,
  SolCompilerTemporaryUnavailable:
    'SolCompilerTemporaryUnavailable' as ErrorCode,
  BlockchainEndpointServiceTemporaryUnavailable:
    'BlockchainEndpointServiceTemporaryUnavailable' as ErrorCode,
  GetBlockchainEndpointCallsFailed:
    'GetBlockchainEndpointCallsFailed' as ErrorCode,
  GetBlockchainEndpointMethodUsageFailed:
    'GetBlockchainEndpointMethodUsageFailed' as ErrorCode,
  GetBlockchainEndpointUsageFailed:
    'GetBlockchainEndpointUsageFailed' as ErrorCode,
  GetBlockchainEndpointCallStatsFailed:
    'GetBlockchainEndpointCallStatsFailed' as ErrorCode,
  DeleteBlockchainEndpointFailed: 'DeleteBlockchainEndpointFailed' as ErrorCode,
  GetBlockchainEndpointsFailed: 'GetBlockchainEndpointsFailed' as ErrorCode,
  CannotGetUserInfo: 'CannotGetUserInfo' as ErrorCode,
  UserAuthenticatedWithDifferentMethod:
    'UserAuthenticatedWithDifferentMethod' as ErrorCode,
  InvalidAccessToken: 'InvalidAccessToken' as ErrorCode,
  CannotActivateAuthMethod: 'CannotActivateAuthMethod' as ErrorCode,
  RpcCallFailed: 'RpcCallFailed' as ErrorCode,
  RpcRequestFailed: 'RpcRequestFailed' as ErrorCode,
  WalletPasswordNotStrongEnough: 'WalletPasswordNotStrongEnough' as ErrorCode,
  CannotChangeWalletPassword: 'CannotChangeWalletPassword' as ErrorCode,
  CannotGenerateSlug: 'CannotGenerateSlug' as ErrorCode,
  UserAlreadyInvited: 'UserAlreadyInvited' as ErrorCode,
  InvitationNotFound: 'InvitationNotFound' as ErrorCode,
  InvitationEmailMismatch: 'InvitationEmailMismatch' as ErrorCode,
  CannotInviteToPersonalOrganization:
    'CannotInviteToPersonalOrganization' as ErrorCode,
  CannotUpdatePersonalOrganization:
    'CannotUpdatePersonalOrganization' as ErrorCode,
  CannotRemoveYourself: 'CannotRemoveYourself' as ErrorCode,
  MemberNotFound: 'MemberNotFound' as ErrorCode,
  SubscriptionProductNotFound: 'SubscriptionProductNotFound' as ErrorCode,
  SubscriptionMetadataNotFound: 'SubscriptionMetadataNotFound' as ErrorCode,
  PaymentSessionMissing: 'PaymentSessionMissing' as ErrorCode,
  CannotFindActiveSubscription: 'CannotFindActiveSubscription' as ErrorCode,
  SubscriptionNotFound: 'SubscriptionNotFound' as ErrorCode,
  CannotFindSubscriptionLimit: 'CannotFindSubscriptionLimit' as ErrorCode,
  SubscriptionDataMissing: 'SubscriptionDataMissing' as ErrorCode,
  GetOrganizationEndpointConsumptionFailed:
    'GetOrganizationEndpointConsumptionFailed' as ErrorCode,
  CannotRegisterPushClient: 'CannotRegisterPushClient' as ErrorCode,
  OAuthDataIncomplete: 'OAuthDataIncomplete' as ErrorCode,
  AppleVerificationFailed: 'AppleVerificationFailed' as ErrorCode,
  OAuthEmailMissing: 'OAuthEmailMissing' as ErrorCode,
  WalletUsedBySmartContracts: 'WalletUsedBySmartContracts' as ErrorCode,
  EmailMissing: 'EmailMissing' as ErrorCode,
  InvalidCode: 'InvalidCode' as ErrorCode,
  TemplateNotFound: 'TemplateNotFound' as ErrorCode,
  TemplateInputInvalid: 'TemplateInputInvalid' as ErrorCode,
  SmartContractNotBelongToOrganization:
    'SmartContractNotBelongToOrganization' as ErrorCode,
  UserNotActive: 'UserNotActive' as ErrorCode,
  OrganizationCacheClearFailed: 'OrganizationCacheClearFailed' as ErrorCode,
  CannotReadRequest: 'CannotReadRequest' as ErrorCode,
  PaymasterServiceUnavailable: 'PaymasterServiceUnavailable' as ErrorCode,
  CreatePaymasterFailed: 'CreatePaymasterFailed' as ErrorCode,
  GetPaymasterFailed: 'GetPaymasterFailed' as ErrorCode,
  UnsupportedFeature: 'UnsupportedFeature' as ErrorCode,
  PaymasterEndpointNotFound: 'PaymasterEndpointNotFound' as ErrorCode,
};
