/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CustomAttributeData } from './customAttributeData';
import type { RuntimeFieldHandle } from './runtimeFieldHandle';
import type { Type } from './type';
import type { Module } from './module';
import type { FieldAttributes } from './fieldAttributes';
import type { MemberTypes } from './memberTypes';

export interface FieldInfo {
  readonly name?: string | null;
  declaringType?: Type;
  reflectedType?: Type;
  module?: Module;
  readonly customAttributes?: Array<CustomAttributeData> | null;
  readonly isCollectible?: boolean;
  readonly metadataToken?: number;
  memberType?: MemberTypes;
  attributes?: FieldAttributes;
  fieldType?: Type;
  readonly isInitOnly?: boolean;
  readonly isLiteral?: boolean;
  readonly isNotSerialized?: boolean;
  readonly isPinvokeImpl?: boolean;
  readonly isSpecialName?: boolean;
  readonly isStatic?: boolean;
  readonly isAssembly?: boolean;
  readonly isFamily?: boolean;
  readonly isFamilyAndAssembly?: boolean;
  readonly isFamilyOrAssembly?: boolean;
  readonly isPrivate?: boolean;
  readonly isPublic?: boolean;
  readonly isSecurityCritical?: boolean;
  readonly isSecuritySafeCritical?: boolean;
  readonly isSecurityTransparent?: boolean;
  fieldHandle?: RuntimeFieldHandle;
}
export namespace FieldInfo {}
