/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { OrganizationSubscriptionLimitResponse } from './organizationSubscriptionLimitResponse';
import type { SubscriptionStatus } from './subscriptionStatus';
import type { SubscriptionPlanType } from './subscriptionPlanType';

export interface OrganizationSubscriptionResponse {
  planType: SubscriptionPlanType;
  status: SubscriptionStatus;
  stripeMeteredPaymasterSubscriptionItemId?: string | null;
  subscriptionLimit: OrganizationSubscriptionLimitResponse;
}
export namespace OrganizationSubscriptionResponse {}
