/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { CustomAttributeData } from './customAttributeData';
import type { Type } from './type';
import type { MemberInfo } from './memberInfo';
import type { ParameterAttributes } from './parameterAttributes';

export interface ParameterInfo {
  attributes?: ParameterAttributes;
  member?: MemberInfo;
  readonly name?: string | null;
  parameterType?: Type;
  readonly position?: number;
  readonly isIn?: boolean;
  readonly isLcid?: boolean;
  readonly isOptional?: boolean;
  readonly isOut?: boolean;
  readonly isRetval?: boolean;
  readonly defaultValue?: any | null;
  readonly rawDefaultValue?: any | null;
  readonly hasDefaultValue?: boolean;
  readonly customAttributes?: Array<CustomAttributeData> | null;
  readonly metadataToken?: number;
}
export namespace ParameterInfo {}
