/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { TaskCreationOptions } from './taskCreationOptions';
import type { AggregateException } from './aggregateException';
import type { TaskStatus } from './taskStatus';

export interface Task {
  readonly id?: number;
  exception?: AggregateException;
  status?: TaskStatus;
  readonly isCanceled?: boolean;
  readonly isCompleted?: boolean;
  readonly isCompletedSuccessfully?: boolean;
  creationOptions?: TaskCreationOptions;
  readonly asyncState?: any | null;
  readonly isFaulted?: boolean;
}
export namespace Task {}
