/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type TaskStatus =
  | 'Created'
  | 'WaitingForActivation'
  | 'WaitingToRun'
  | 'Running'
  | 'WaitingForChildrenToComplete'
  | 'RanToCompletion'
  | 'Canceled'
  | 'Faulted';

export const TaskStatus = {
  Created: 'Created' as TaskStatus,
  WaitingForActivation: 'WaitingForActivation' as TaskStatus,
  WaitingToRun: 'WaitingToRun' as TaskStatus,
  Running: 'Running' as TaskStatus,
  WaitingForChildrenToComplete: 'WaitingForChildrenToComplete' as TaskStatus,
  RanToCompletion: 'RanToCompletion' as TaskStatus,
  Canceled: 'Canceled' as TaskStatus,
  Faulted: 'Faulted' as TaskStatus,
};
