/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type TaskCreationOptions =
  | 'None'
  | 'PreferFairness'
  | 'LongRunning'
  | 'AttachedToParent'
  | 'DenyChildAttach'
  | 'HideScheduler'
  | 'RunContinuationsAsynchronously';

export const TaskCreationOptions = {
  None: 'None' as TaskCreationOptions,
  PreferFairness: 'PreferFairness' as TaskCreationOptions,
  LongRunning: 'LongRunning' as TaskCreationOptions,
  AttachedToParent: 'AttachedToParent' as TaskCreationOptions,
  DenyChildAttach: 'DenyChildAttach' as TaskCreationOptions,
  HideScheduler: 'HideScheduler' as TaskCreationOptions,
  RunContinuationsAsynchronously:
    'RunContinuationsAsynchronously' as TaskCreationOptions,
};
