/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type TypeAttributes =
  | 'NotPublic'
  | 'AutoLayout'
  | 'AnsiClass'
  | 'Class'
  | 'Public'
  | 'NestedPublic'
  | 'NestedPrivate'
  | 'NestedFamily'
  | 'NestedAssembly'
  | 'NestedFamANDAssem'
  | 'NestedFamORAssem'
  | 'VisibilityMask'
  | 'SequentialLayout'
  | 'ExplicitLayout'
  | 'LayoutMask'
  | 'Interface'
  | 'ClassSemanticsMask'
  | 'Abstract'
  | 'Sealed'
  | 'SpecialName'
  | 'RTSpecialName'
  | 'Import'
  | 'Serializable'
  | 'WindowsRuntime'
  | 'UnicodeClass'
  | 'AutoClass'
  | 'CustomFormatClass'
  | 'StringFormatMask'
  | 'HasSecurity'
  | 'ReservedMask'
  | 'BeforeFieldInit'
  | 'CustomFormatMask';

export const TypeAttributes = {
  NotPublic: 'NotPublic' as TypeAttributes,
  AutoLayout: 'AutoLayout' as TypeAttributes,
  AnsiClass: 'AnsiClass' as TypeAttributes,
  Class: 'Class' as TypeAttributes,
  Public: 'Public' as TypeAttributes,
  NestedPublic: 'NestedPublic' as TypeAttributes,
  NestedPrivate: 'NestedPrivate' as TypeAttributes,
  NestedFamily: 'NestedFamily' as TypeAttributes,
  NestedAssembly: 'NestedAssembly' as TypeAttributes,
  NestedFamAndAssem: 'NestedFamANDAssem' as TypeAttributes,
  NestedFamOrAssem: 'NestedFamORAssem' as TypeAttributes,
  VisibilityMask: 'VisibilityMask' as TypeAttributes,
  SequentialLayout: 'SequentialLayout' as TypeAttributes,
  ExplicitLayout: 'ExplicitLayout' as TypeAttributes,
  LayoutMask: 'LayoutMask' as TypeAttributes,
  Interface: 'Interface' as TypeAttributes,
  ClassSemanticsMask: 'ClassSemanticsMask' as TypeAttributes,
  Abstract: 'Abstract' as TypeAttributes,
  Sealed: 'Sealed' as TypeAttributes,
  SpecialName: 'SpecialName' as TypeAttributes,
  RtSpecialName: 'RTSpecialName' as TypeAttributes,
  Import: 'Import' as TypeAttributes,
  Serializable: 'Serializable' as TypeAttributes,
  WindowsRuntime: 'WindowsRuntime' as TypeAttributes,
  UnicodeClass: 'UnicodeClass' as TypeAttributes,
  AutoClass: 'AutoClass' as TypeAttributes,
  CustomFormatClass: 'CustomFormatClass' as TypeAttributes,
  StringFormatMask: 'StringFormatMask' as TypeAttributes,
  HasSecurity: 'HasSecurity' as TypeAttributes,
  ReservedMask: 'ReservedMask' as TypeAttributes,
  BeforeFieldInit: 'BeforeFieldInit' as TypeAttributes,
  CustomFormatMask: 'CustomFormatMask' as TypeAttributes,
};
