/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type WalletActivity =
  | 'ContractCreation'
  | 'ContractCall'
  | 'RpcCall'
  | 'PasswordChange';

export const WalletActivity = {
  ContractCreation: 'ContractCreation' as WalletActivity,
  ContractCall: 'ContractCall' as WalletActivity,
  RpcCall: 'RpcCall' as WalletActivity,
  PasswordChange: 'PasswordChange' as WalletActivity,
};
