/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { UserResponse } from './userResponse';
import type { SmartContractLightResponse } from './smartContractLightResponse';
import type { BlockchainResponse } from './blockchainResponse';
import type { WalletActivity } from './walletActivity';

export interface WalletActivityResponse {
  id: string;
  activity: WalletActivity;
  smartContractMethod?: string | null;
  rpcMethod?: string | null;
  callParams?: string | null;
  smartContract?: SmartContractLightResponse;
  blockchain?: BlockchainResponse;
  user?: UserResponse;
  createdAt: string;
}
export namespace WalletActivityResponse {}
