/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EndpointCallStatus = 'Success' | 'Error';

export const EndpointCallStatus = {
    Success: 'Success' as EndpointCallStatus,
    Error: 'Error' as EndpointCallStatus
};

