/**
 * Kriptonio Private API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: private
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { DataPeriod } from './dataPeriod';
import type { EndpointCallStatus } from './endpointCallStatus';


export interface GetBlockchainCallsBody { 
    filterByCallStatus: Array<EndpointCallStatus>;
    filterByMethod: Array<string>;
    page: number;
    pageSize: number;
    period: DataPeriod;
}
export namespace GetBlockchainCallsBody {
}


